import { Construction } from 'lucide-react';

export default function RollYield() {
  return (
    <>
      <section className="container page-intro">
        <p className="eyebrow">Roll Yield</p>
        <h1 className="page-title">Bonds rolling down the curve.</h1>
        <p className="page-lede">
          Carry on a fixed income position combines two pieces: the yield you earn simply by holding
          the bond (the &ldquo;level&rdquo;), and the capital gain as the bond rolls down an
          upward-sloping curve toward lower yields (the &ldquo;roll-down&rdquo;).
        </p>
      </section>

      <section className="container roll-yield-section">
        <figure className="roll-yield-figure">
          <img
            src="/roll-yield-carry.png"
            alt="Fixed Income Carry: combining the level and roll-down components. A yield curve where the 'Level' is the yield benefit accrued through holding a security over a period of time, and the 'Roll-Down' is the capital gain realised through the fall in yield generated by the slope of the curve."
          />
        </figure>
        <div className="roll-yield-dev">
          <Construction size={18} />
          <span>
            <strong>Under development.</strong> An interactive roll-down and carry calculator is on the
            way. This illustration previews the concept.
          </span>
        </div>
      </section>
    </>
  );
}
